# Generated by Django 4.0.4 on 2022-05-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventStatus',
        ),
    ]
