# Generated by Django 4.0.4 on 2022-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_contract_amount_contract_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
