# Generated by Django 4.0.4 on 2022-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_phone_alter_event_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contract',
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
