# Generated by Django 4.0.4 on 2022-05-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_event_contract_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event', serialize=False, to='clients.contract'),
            preserve_default=False,
        ),
    ]
