# Generated by Django 4.0.4 on 2022-05-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_event_id_event_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
